#!/usr/bin/env bash
# Build a Mixer firmware image for the nRF52840 USB Dongle (PCA10059) with a
# baked-in node id, then wrap it in a DFU package ready for the open
# bootloader. Output goes into tutorial/nRF52840/build/node<ID>/.
#
# Usage:
#   scripts/build_node.sh <node_id> [--round-length N] [--slot-us US]
#
# Optional rate tuning (both nodes must use identical values):
#   --round-length N   override MX_ROUND_LENGTH (default in mixer_config.h: 50)
#   --slot-us US       override MX_SLOT_LENGTH = GPI_TICK_US_TO_HYBRID2(US)
#                      (default in mixer_config.h: 2000)
#
# Round period is roughly proportional to round_length * slot_us (plus PHY
# overhead -- measured 50 * 2000us -> ~1.10s on this build, i.e. ~0.91 Hz).
# Halving round_length roughly doubles the host publish rate ceiling.
#
# Both overrides edit mixer_config.h in place; the original is restored on
# exit (success or failure) via a trap, so the working tree stays clean.
#
# Environment overrides:
#   SES_DIR     -- root of the SEGGER Embedded Studio install (default: 5.70a)
#   NRFUTIL     -- path to the nrfutil binary (default: ~/.local/bin/nrfutil)
#
# Exits non-zero on any failure. Prints final hex/zip paths on success.

set -euo pipefail

usage() {
    sed -n '2,18p' "$0" | sed 's/^# \?//'
    exit 2
}

NODE_ID=""
ROUND_LENGTH=""
SLOT_US=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --round-length)
            ROUND_LENGTH="${2:-}"
            shift 2 || usage
            ;;
        --slot-us)
            SLOT_US="${2:-}"
            shift 2 || usage
            ;;
        -h|--help)
            usage
            ;;
        --*)
            echo "error: unknown option '$1'" >&2
            usage
            ;;
        *)
            if [[ -n "$NODE_ID" ]]; then
                echo "error: extra positional argument '$1'" >&2
                usage
            fi
            NODE_ID="$1"
            shift
            ;;
    esac
done

if [[ -z "$NODE_ID" ]]; then
    echo "error: <node_id> is required" >&2
    usage
fi
if ! [[ "$NODE_ID" =~ ^[0-9]+$ ]] || (( NODE_ID < 1 || NODE_ID > 254 )); then
    echo "error: node_id must be an integer in [1, 254], got '$NODE_ID'" >&2
    exit 2
fi
if [[ -n "$ROUND_LENGTH" ]] \
   && ! { [[ "$ROUND_LENGTH" =~ ^[0-9]+$ ]] && (( ROUND_LENGTH >= 1 && ROUND_LENGTH <= 255 )); }; then
    echo "error: --round-length must be an integer in [1, 255], got '$ROUND_LENGTH'" >&2
    exit 2
fi
if [[ -n "$SLOT_US" ]] \
   && ! { [[ "$SLOT_US" =~ ^[0-9]+$ ]] && (( SLOT_US >= 100 && SLOT_US <= 1000000 )); }; then
    echo "error: --slot-us must be an integer in [100, 1000000], got '$SLOT_US'" >&2
    exit 2
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TUTORIAL_DIR="$REPO_ROOT/tutorial/nRF52840"
PROJECT="$TUTORIAL_DIR/tutorial.emProject"
CONFIG="PCA10059_Release"

SES_DIR="${SES_DIR:-/usr/share/segger_embedded_studio_for_arm_5.70a}"
EMBUILD="$SES_DIR/bin/emBuild"
NRFUTIL="${NRFUTIL:-$HOME/.local/bin/nrfutil}"

if [[ ! -x "$EMBUILD" ]]; then
    echo "error: emBuild not found at $EMBUILD" >&2
    echo "  set SES_DIR to the root of your SES install" >&2
    exit 1
fi
if [[ ! -x "$NRFUTIL" ]]; then
    echo "error: nrfutil not found at $NRFUTIL" >&2
    echo "  install with:" >&2
    echo "    curl -L https://files.nordicsemi.com/artifactory/swtools/external/nrfutil/executables/x86_64-unknown-linux-gnu/nrfutil -o $NRFUTIL" >&2
    echo "    chmod +x $NRFUTIL && $NRFUTIL install nrf5sdk-tools" >&2
    exit 1
fi

OUT_DIR="$TUTORIAL_DIR/build/node${NODE_ID}"
mkdir -p "$OUT_DIR"

# Inject the node id by writing a small header next to main.c. main.c uses
# __has_include to pick this up automatically and falls back to BUILD_NODE_ID=0
# (interactive UICR path) when the header is absent.
NODE_ID_HDR="$TUTORIAL_DIR/node_id.h"
cat > "$NODE_ID_HDR" <<EOF
// Generated by scripts/build_node.sh -- do not edit manually.
// Removing this file restores the interactive UICR-based id workflow.
#define BUILD_NODE_ID ${NODE_ID}
EOF

echo "[build_node] node_id=${NODE_ID} -> ${OUT_DIR}"

# Apply --round-length / --slot-us by patching mixer_config.h in place. Always
# restore the original on exit so the working tree stays clean even if the
# build (or a Ctrl-C) interrupts us.
MIXER_CFG="$TUTORIAL_DIR/mixer_config.h"
MIXER_CFG_BAK=""
if [[ -n "$ROUND_LENGTH" || -n "$SLOT_US" ]]; then
    MIXER_CFG_BAK="$(mktemp -p "$TUTORIAL_DIR" mixer_config.h.bak.XXXXXX)"
    cp "$MIXER_CFG" "$MIXER_CFG_BAK"
    trap 'cp "$MIXER_CFG_BAK" "$MIXER_CFG"; rm -f "$MIXER_CFG_BAK"' EXIT

    if [[ -n "$ROUND_LENGTH" ]]; then
        # Match: '#define MX_ROUND_LENGTH<ws><digits>' optionally followed by '//' comment
        sed -E -i "s|^([[:space:]]*#define[[:space:]]+MX_ROUND_LENGTH[[:space:]]+)[0-9]+|\1${ROUND_LENGTH}|" "$MIXER_CFG"
        if ! grep -qE "^[[:space:]]*#define[[:space:]]+MX_ROUND_LENGTH[[:space:]]+${ROUND_LENGTH}\\b" "$MIXER_CFG"; then
            echo "error: failed to patch MX_ROUND_LENGTH in $MIXER_CFG" >&2
            exit 1
        fi
        echo "[build_node] patched MX_ROUND_LENGTH = ${ROUND_LENGTH}"
    fi
    if [[ -n "$SLOT_US" ]]; then
        # Match the active line: '#define MX_SLOT_LENGTH ... GPI_TICK_US_TO_HYBRID2(<digits>)'
        # Leaves the commented-out '// #define MX_SLOT_LENGTH ...' alternative untouched.
        sed -E -i "s|^([[:space:]]*#define[[:space:]]+MX_SLOT_LENGTH[[:space:]]+GPI_TICK_US_TO_HYBRID2\\()[0-9]+(\\))|\1${SLOT_US}\2|" "$MIXER_CFG"
        if ! grep -qE "^[[:space:]]*#define[[:space:]]+MX_SLOT_LENGTH[[:space:]]+GPI_TICK_US_TO_HYBRID2\\(${SLOT_US}\\)" "$MIXER_CFG"; then
            echo "error: failed to patch MX_SLOT_LENGTH in $MIXER_CFG" >&2
            exit 1
        fi
        echo "[build_node] patched MX_SLOT_LENGTH = GPI_TICK_US_TO_HYBRID2(${SLOT_US})"
    fi
fi

cd "$TUTORIAL_DIR"

"$EMBUILD" -config "$CONFIG" -rebuild "$PROJECT"

SRC_HEX="$TUTORIAL_DIR/Output/$CONFIG/Exe/Tutorial.hex"
SRC_ELF="$TUTORIAL_DIR/Output/$CONFIG/Exe/Tutorial.elf"
if [[ ! -f "$SRC_HEX" ]]; then
    echo "error: build did not produce $SRC_HEX" >&2
    exit 1
fi

DST_HEX="$OUT_DIR/Tutorial_node${NODE_ID}.hex"
DST_ELF="$OUT_DIR/Tutorial_node${NODE_ID}.elf"
DST_ZIP="$OUT_DIR/mixer_node${NODE_ID}.zip"

cp "$SRC_HEX" "$DST_HEX"
cp "$SRC_ELF" "$DST_ELF"

# Verify the requested id was actually baked into TOS_NODE_ID by reading the
# .data symbol back. Catches header-not-picked-up bugs early.
NM_PATH="$SES_DIR/gcc/arm-none-eabi/bin/nm"
OBJDUMP_PATH="$SES_DIR/gcc/arm-none-eabi/bin/objdump"
if [[ -x "$NM_PATH" && -x "$OBJDUMP_PATH" ]]; then
    TOS_ADDR=$("$NM_PATH" "$DST_ELF" | awk '$3=="TOS_NODE_ID"{print $1}' | head -n1)
    if [[ -n "$TOS_ADDR" ]]; then
        STOP_ADDR=$(printf "0x%x" $((0x$TOS_ADDR + 4)))
        BAKED=$("$OBJDUMP_PATH" -s --start-address="0x$TOS_ADDR" --stop-address="$STOP_ADDR" "$DST_ELF" \
            | awk '/Contents of section/{f=1;next} f && NF>=2 {print $2; exit}')
        if [[ -n "$BAKED" ]]; then
            BAKED_LE=$(echo "$BAKED" | sed -E 's/(..)(..)(..)(..)/\4\3\2\1/')
            BAKED_DEC=$((16#$BAKED_LE))
            if [[ "$BAKED_DEC" -ne "$NODE_ID" ]]; then
                echo "error: baked TOS_NODE_ID=$BAKED_DEC does not match requested $NODE_ID" >&2
                echo "  raw bytes at $TOS_ADDR: $BAKED" >&2
                exit 1
            fi
            echo "[build_node] verified TOS_NODE_ID=$BAKED_DEC at $TOS_ADDR"
        fi
    fi
fi

# Wrap into a DFU package compatible with the Dongle's open bootloader.
# --sd-req 0x00 = no SoftDevice. application-version is bumped per-id so
# re-flashing the same node never gets rejected as "downgrade".
APP_VER=$((NODE_ID + 1))
"$NRFUTIL" nrf5sdk-tools pkg generate \
    --hw-version 52 \
    --sd-req 0x00 \
    --application "$DST_HEX" \
    --application-version "$APP_VER" \
    "$DST_ZIP" >/dev/null

echo "[build_node] hex: $DST_HEX"
echo "[build_node] zip: $DST_ZIP"
