#!/usr/bin/env bash
# Build a Mixer firmware image for the nRF52840 USB Dongle (PCA10059) with a
# baked-in node id, then wrap it in a DFU package ready for the open
# bootloader. Output goes into tutorial/nRF52840/build/node<ID>/.
#
# Usage:
#   scripts/build_node.sh <node_id>
#
# Environment overrides:
#   SES_DIR     -- root of the SEGGER Embedded Studio install (default: 5.70a)
#   NRFUTIL     -- path to the nrfutil binary (default: ~/.local/bin/nrfutil)
#
# Exits non-zero on any failure. Prints final hex/zip paths on success.

set -euo pipefail

if [[ $# -ne 1 ]]; then
    echo "usage: $0 <node_id>" >&2
    exit 2
fi

NODE_ID="$1"
if ! [[ "$NODE_ID" =~ ^[0-9]+$ ]] || (( NODE_ID < 1 || NODE_ID > 254 )); then
    echo "error: node_id must be an integer in [1, 254], got '$NODE_ID'" >&2
    exit 2
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TUTORIAL_DIR="$REPO_ROOT/tutorial/nRF52840"
PROJECT="$TUTORIAL_DIR/tutorial.emProject"
CONFIG="PCA10059_Release"

SES_DIR="${SES_DIR:-/usr/share/segger_embedded_studio_for_arm_5.70a}"
EMBUILD="$SES_DIR/bin/emBuild"
NRFUTIL="${NRFUTIL:-$HOME/.local/bin/nrfutil}"

if [[ ! -x "$EMBUILD" ]]; then
    echo "error: emBuild not found at $EMBUILD" >&2
    echo "  set SES_DIR to the root of your SES install" >&2
    exit 1
fi
if [[ ! -x "$NRFUTIL" ]]; then
    echo "error: nrfutil not found at $NRFUTIL" >&2
    echo "  install with:" >&2
    echo "    curl -L https://files.nordicsemi.com/artifactory/swtools/external/nrfutil/executables/x86_64-unknown-linux-gnu/nrfutil -o $NRFUTIL" >&2
    echo "    chmod +x $NRFUTIL && $NRFUTIL install nrf5sdk-tools" >&2
    exit 1
fi

OUT_DIR="$TUTORIAL_DIR/build/node${NODE_ID}"
mkdir -p "$OUT_DIR"

# Inject the node id by writing a small header next to main.c. main.c uses
# __has_include to pick this up automatically and falls back to BUILD_NODE_ID=0
# (interactive UICR path) when the header is absent.
NODE_ID_HDR="$TUTORIAL_DIR/node_id.h"
cat > "$NODE_ID_HDR" <<EOF
// Generated by scripts/build_node.sh -- do not edit manually.
// Removing this file restores the interactive UICR-based id workflow.
#define BUILD_NODE_ID ${NODE_ID}
EOF

echo "[build_node] node_id=${NODE_ID} -> ${OUT_DIR}"
cd "$TUTORIAL_DIR"

"$EMBUILD" -config "$CONFIG" -rebuild "$PROJECT"

SRC_HEX="$TUTORIAL_DIR/Output/$CONFIG/Exe/Tutorial.hex"
SRC_ELF="$TUTORIAL_DIR/Output/$CONFIG/Exe/Tutorial.elf"
if [[ ! -f "$SRC_HEX" ]]; then
    echo "error: build did not produce $SRC_HEX" >&2
    exit 1
fi

DST_HEX="$OUT_DIR/Tutorial_node${NODE_ID}.hex"
DST_ELF="$OUT_DIR/Tutorial_node${NODE_ID}.elf"
DST_ZIP="$OUT_DIR/mixer_node${NODE_ID}.zip"

cp "$SRC_HEX" "$DST_HEX"
cp "$SRC_ELF" "$DST_ELF"

# Verify the requested id was actually baked into TOS_NODE_ID by reading the
# .data symbol back. Catches header-not-picked-up bugs early.
NM_PATH="$SES_DIR/gcc/arm-none-eabi/bin/nm"
OBJDUMP_PATH="$SES_DIR/gcc/arm-none-eabi/bin/objdump"
if [[ -x "$NM_PATH" && -x "$OBJDUMP_PATH" ]]; then
    TOS_ADDR=$("$NM_PATH" "$DST_ELF" | awk '$3=="TOS_NODE_ID"{print $1}' | head -n1)
    if [[ -n "$TOS_ADDR" ]]; then
        STOP_ADDR=$(printf "0x%x" $((0x$TOS_ADDR + 4)))
        BAKED=$("$OBJDUMP_PATH" -s --start-address="0x$TOS_ADDR" --stop-address="$STOP_ADDR" "$DST_ELF" \
            | awk '/Contents of section/{f=1;next} f && NF>=2 {print $2; exit}')
        if [[ -n "$BAKED" ]]; then
            BAKED_LE=$(echo "$BAKED" | sed -E 's/(..)(..)(..)(..)/\4\3\2\1/')
            BAKED_DEC=$((16#$BAKED_LE))
            if [[ "$BAKED_DEC" -ne "$NODE_ID" ]]; then
                echo "error: baked TOS_NODE_ID=$BAKED_DEC does not match requested $NODE_ID" >&2
                echo "  raw bytes at $TOS_ADDR: $BAKED" >&2
                exit 1
            fi
            echo "[build_node] verified TOS_NODE_ID=$BAKED_DEC at $TOS_ADDR"
        fi
    fi
fi

# Wrap into a DFU package compatible with the Dongle's open bootloader.
# --sd-req 0x00 = no SoftDevice. application-version is bumped per-id so
# re-flashing the same node never gets rejected as "downgrade".
APP_VER=$((NODE_ID + 1))
"$NRFUTIL" nrf5sdk-tools pkg generate \
    --hw-version 52 \
    --sd-req 0x00 \
    --application "$DST_HEX" \
    --application-version "$APP_VER" \
    "$DST_ZIP" >/dev/null

echo "[build_node] hex: $DST_HEX"
echo "[build_node] zip: $DST_ZIP"
